const db = require('./server/db')
const chalk = require('chalk')
const { Product, Category, Review, ProductCategory, Cart, LineItem, Bid, BidArea, AreaProduct, User, Customer, Contact } = require('./server/db/models')

const markup = cost => (cost * 1.3).toFixed(2)
const applyDiscount = cost => cost * .6

const findProp = (products, productId, prop) => {
 return products.filter(product => product.id === productId)[0][prop]
}

async function seed () {
  await db.sync({force: true})
  console.log(chalk.bgGreen.white.bold('db synced!'))

  const users = await Promise.all([
    User.create({firstName: 'cody', lastName: 'greene', email: 'cody@email.com', password: '123', isAdmin: true}),
    User.create({firstName: 'eddie', lastName: 'murphy', email: 'murphy@email.com', password: '123', phone: '2125555555'})
  ])

  const customers = await Promise.all([
    Customer.create({ companyName: "Palm City Yachts", industry: "Marine",  address: "2901 SE Gran Park Way", town: "Stuart, FL", zipCode: "34994", localPolicePhone: "772-287-1122", email: "palmcitytest@email.com", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "2nd Chance Salvage", industry: "Junk Yard", address: "1303 Angle Road", town: "Fort Pierce, FL", zipCode: "34947", localPolicePhone: "772-462-7300", email: "", relayPort: "9011", relayId: "1" }),
    Customer.create({ companyName: "Atlis Little Havana", industry: "Construction", address: "", town: "Miami, FL", zipCode: "33135", localPolicePhone: "305-579-6111", email: "", relayPort: "9011", relayId: "3" }),
    Customer.create({ companyName: "CBS Corpus Christi", industry: "Equipment Rental", address: "7219 I-37 Frontage Rd", town: "Corpus Christi, TX", zipCode: "78409", localPolicePhone: "361-886-2600", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "CBS San Antonio", industry: "Equipment Rental", address: "11500 N North Loop Rd", town: "San Antonio, TX", zipCode: "78217", localPolicePhone: "210-207-7273", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "CBS Houston", industry: "Equipment Rental", address: "8660 S Loop E Freeway", town: "Houston, TX", zipCode: "77017", localPolicePhone: "713-884-3131", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "CBS Longview", industry: "Equipment Rental", address: "4622 W. Loop 281", town: "Longview, TX", zipCode: "75604", localPolicePhone: "903-237-1199", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "CBS Tyler", industry: "Equipment Rental", address: "401 N NE 323 Loop", town: "Tyler, TX", zipCode: "75708", localPolicePhone: "903-531-1000", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "CBS Conroe", industry: "Equipment Rental", address: "610 N. Loop 366 W.", town: "Conroe, TX", zipCode: "77301", localPolicePhone: "936-522-3200", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "CBS Austin", industry: "Equipment Rental", address: "109 US-183", town: "Austin, TX", zipCode: "78747", localPolicePhone: "512-854-9770", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "CBS Arlington", industry: "Equipment Rental", address: "601 N. Great SW Pkwy", town: "Arlington, TX", zipCode: "76011", localPolicePhone: "817-459-5700", email: "", relayPort: "9011", relayId: "4" }),
    Customer.create({ companyName: "CBS Caddo Mills", industry: "Equipment Rental", address: "4899 W. Interstate 30", town: "Caddo Mills, TX", zipCode: "75135", localPolicePhone: "903-527-3122", email: "", relayPort: "9015", relayId: "3" }),
    Customer.create({ companyName: "CBS Odessa", industry: "Equipment Rental", address: "12501 W. I-20 E", town: "Odessa, TX", zipCode: "79765", localPolicePhone: "432-333-3641", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "CBS Bryan", industry: "Equiment Rental", address: "610 N. Loop 366 W.", town: "Conroe, TX", zipCode: "77201", localPolicePhone: "936-522-3200", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "CBS Carlsbad", industry: "Equipment Rental", address: "4620 National Parks Hwy", town: "Carlsbad, NM", zipCode: "88220", localPolicePhone: "", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "Grounds Group", industry: "Landscaping", address: "1110 S. Flamingo Rd.", town: "Davis, FL", zipCode: "33325", localPolicePhone: "", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "Lions Plumbing", industry: "Plumbing", address: "14350 NW 7th Ave", town: "Miami, FL", zipCode: "33168", localPolicePhone: "305-476-5423", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "Miami Shores", industry: "Public Works", address: "620 NE 126th St.", town: "Miami, FL", zipCode: "33161", localPolicePhone: "305-759-2468", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "Sunbelt PC-019", industry: "Equipment Rental", address: "6550 NW 77th Ct.", town: "Miami, FL", zipCode: "33166", localPolicePhone: "305-471-2800", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "Sunbelt PC-080", industry: "Equipment Rental", address: "21100 Sheridan St.", town: "Pembroke Pines, FL", zipCode: "33332", localPolicePhone: "954-431-2200", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "Sunbelt PC-090", industry: "Equipment Rental", address: "5770 N. Military Trail", town: "West Palm Beach, FL", zipCode: "33407", localPolicePhone: "", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "Sunbelt PC-115", industry: "Equipment Rental", address: "65 NE 27th St.", town: "Miami, FL", zipCode: "33137", localPolicePhone: "305-603-6640", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "Sunbelt PC-249", industry: "Equipment Rental", address: "1450 NE 1st Ave", town: "Florida City, FL", zipCode: "33034", localPolicePhone: "305-247-8220", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "Sunbelt PC-507", industry: "Equipment Rental", address: "2700 South Federal Hwy", town: "Hollywood, FL", zipCode: "33316", localPolicePhone: "954-754-4957", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "Atlantic Southern Paving", industry: "Work Yard", address: "", town: "Fort Pierce, FL", zipCode: "34947", localPolicePhone: "772-462-7300", email: "", relayPort: "9011", relayId: "2" }),
    Customer.create({ companyName: "Wilco Baron & Sign", industry: "Electric", address: "900 W. 13th St.", town: "Riviera Beach, FL", zipCode: "33403", localPolicePhone: "561-845-4123", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "Wilco St. Lucie", industry: "Electric", address: "1303 Angle Road", town: "Fort Pierce, FL", zipCode: "34947", localPolicePhone: "772-462-7300", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "Wilco Royal Palm", industry: "Electric", address: "430 Business Parkway", town: "Royal Palm Beach, FL", zipCode: "33421", localPolicePhone: "561-790-5180", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "Global Parts Supply", industry: "Retail", address: "2550/2595NW 4th Court", town: "Fort Lauderdale, FL", zipCode: "33311", localPolicePhone: "", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "ISS Mechanical", industry: "Outdoor Storage", address: "3144 N John Young Pkwy", town: "Orlando, FL", zipCode: "32804", localPolicePhone: "321-253-5300", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "Offshore Marine", industry: "Marine", address: "2135 N. Old Dixie Hwy", town: "Fort Pierce, FL", zipCode: "34946", localPolicePhone: "772-462-7300", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "Parks Rental St. Lucie", industry: "Equipment Rental", address: "1676 SW Baltimore St", town: "Port St. Lucie, FL", zipCode: "34984", localPolicePhone: "772-871-5000", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "Parks Rental Vero Beach", industry: "Equipment Rental", address: "1230 16th St", town: "Vero Beach, FL", zipCode: "32960", localPolicePhone: "772-978-4600", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "Parks Rental Fort Pierce", industry: "Equipment Rental", address: "2306 Okeechobee Road", town: "Fort Pierce, FL", zipCode: "34950", localPolicePhone: "772-467-6800", email: "", relayPort: "9015", relayId: "4" }),
    Customer.create({ companyName: "Regency Party Rentals", industry: "Rental", address: "5900 N. Austrailian Ave", town: "West Palm Beach, FL", zipCode: "33407", localPolicePhone: "561-688-3000", email: "", relayPort: "9015", relayId: "4" })
  ])

  const contacts = await Promise.all([
    Contact.create({ firstName: "Chris", lastName: "", phoneNumber: "772-370-7479", email: "", primary: true, customerId: customers[1].id }),
    Contact.create({ firstName: "Oscar", lastName: "Rodriguez", phoneNumber: "361-945-3200", email: "oscar.rodriguez@teamcbs.com", primary: true, customerId: customers[3].id }),
    Contact.create({ firstName: "Brad", lastName: "Rodgers", phoneNumber: "361-290-8954", email: "brad.rodgers@teamcbs.com", primary: false, customerId: customers[3].id }),
    Contact.create({ firstName: "Luis", lastName: "Sepulveda", phoneNumber: "361-290-8954", email: "luis.sepulveda@teamcbs.com", primary: false, customerId: customers[3].id }),
    Contact.create({ firstName: "Stephen", lastName: "Starr", phoneNumber: "210-838-8759", email: "", primary: true, customerId: customers[4].id }),
    Contact.create({ firstName: "Mauicio", lastName: "Moreno", phoneNumber: "361-424-1263", email: "", primary: true, customerId: customers[4].id }),
    Contact.create({ firstName: "Juanjose", lastName: "Bravo", phoneNumber: "210-291-2325", email: "", primary: true, customerId: customers[4].id }),
    Contact.create({ firstName: "Charles", lastName: "Douglas", phoneNumber: "210-669-9865", email: "", primary: false, customerId: customers[4].id }),
    Contact.create({ firstName: "Juan", lastName: "Garcia", phoneNumber: "210-884-2546", email: "", primary: false, customerId: customers[4].id }),
    Contact.create({ firstName: "Jorge", lastName: "Zamora", phoneNumber: "210-776-4750", email: "", primary: false, customerId: customers[4].id }),
    Contact.create({ firstName: "Juan", lastName: "Esobedo", phoneNumber: "830-317-0955", email: "", primary: false, customerId: customers[4].id }),
    Contact.create({ firstName: "Matthew", lastName: "Organ", phoneNumber: "281-739-1474", email: "", primary: false, customerId: customers[4].id }),
    Contact.create({ firstName: "Nicholas", lastName: "Morn", phoneNumber: "210-363-5804", email: "", primary: false, customerId: customers[4].id }),
    Contact.create({ firstName: "Daniel", lastName: "Torres", phoneNumber: "210-254-6237", email: "", primary: false, customerId: customers[4].id }),
    Contact.create({ firstName: "David", lastName: "Isbell", phoneNumber: "210-849-0575", email: "", primary: false, customerId: customers[4].id }),
    Contact.create({ firstName: "Marcos", lastName: "Soto", phoneNumber: "602-390-0784", email: "", primary: false, customerId: customers[4].id }),
    Contact.create({ firstName: "Carly", lastName: "Holliday", phoneNumber: "832-853-1258", email: "carly.holliday@teamcbs.com", primary: true, customerId: customers[5].id }),
    Contact.create({ firstName: "Robert", lastName: "Bass", phoneNumber: "713-817-2063", email: "robert.bass@teamcbs.com", primary: false, customerId: customers[5].id }),
    Contact.create({ firstName: "Kevin", lastName: "Williams", phoneNumber: "N/A", email: "kevin.williams@teamcbs.com", primary: false, customerId: customers[5].id }),
    Contact.create({ firstName: "Rachel", lastName: "Levy", phoneNumber: "318-455-8710", email: "", primary: true, customerId: customers[6].id }),
    Contact.create({ firstName: "Kendon", lastName: "Bacon", phoneNumber: "903-985-9765", email: "", primary: false, customerId: customers[6].id }),
    Contact.create({ firstName: "Heather", lastName: "Loyd", phoneNumber: "903-880-2388", email: "", primary: false, customerId: customers[6].id }),
    Contact.create({ firstName: "Trent", lastName: "Ledkins", phoneNumber: "903-253-3872", email: "", primary: false, customerId: customers[6].id }),
    Contact.create({ firstName: "Jorge", lastName: "Callejas", phoneNumber: "903-424-7845", email: "", primary: false, customerId: customers[6].id }),
    Contact.create({ firstName: "Cliff", lastName: "Askew", phoneNumber: "903-880-7672", email: "", primary: false, customerId: customers[6].id }),
    Contact.create({ firstName: "Coty", lastName: "Johnson", phoneNumber: "903-238-1839", email: "", primary: false, customerId: customers[6].id }),
    Contact.create({ firstName: "Jeremy", lastName: "Moore", phoneNumber: "903-806-1087", email: "", primary: false, customerId: customers[6].id }),
    Contact.create({ firstName: "Jon", lastName: "Monk", phoneNumber: "903-452-7989", email: "", primary: false, customerId: customers[6].id }),
    Contact.create({ firstName: "Donald", lastName: "Ramsey", phoneNumber: "903-578-1195", email: "", primary: false, customerId: customers[6].id }),
    Contact.create({ firstName: "Brandon", lastName: "Lowe", phoneNumber: "903-240-9357", email: "", primary: false, customerId: customers[6].id }),
    Contact.create({ firstName: "Kelly", lastName: "Bunt", phoneNumber: "903-738-0032", email: "", primary: false, customerId: customers[6].id }),
    Contact.create({ firstName: "Glenn", lastName: "Sparks", phoneNumber: "903-508-9692", email: "", primary: false, customerId: customers[6].id }),
    Contact.create({ firstName: "Casey", lastName: "Hitchcock", phoneNumber: "903-465-1522", email: "", primary: false, customerId: customers[6].id }),
    Contact.create({ firstName: "David", lastName: "Martinez", phoneNumber: "903-407-8246", email: "", primary: true, customerId: customers[7].id }),
    Contact.create({ firstName: "Casey", lastName: "Hitchcock", phoneNumber: "903-465-1522", email: "", primary: false, customerId: customers[7].id }),
    Contact.create({ firstName: "Michael", lastName: "Morgan", phoneNumber: "903-275-6903", email: "", primary: false, customerId: customers[7].id }),
    Contact.create({ firstName: "Daniel", lastName: "Harris", phoneNumber: "903-805-1507", email: "", primary: false, customerId: customers[7].id }),
    Contact.create({ firstName: "Kyle", lastName: "Harris", phoneNumber: "903-360-7612", email: "", primary: false, customerId: customers[7].id }),
    Contact.create({ firstName: "Clifton", lastName: "Coe", phoneNumber: "N/A", email: "", primary: false, customerId: customers[7].id }),
    Contact.create({ firstName: "Paul", lastName: "Lockett", phoneNumber: "903-658-0778", email: "", primary: false, customerId: customers[7].id }),
    Contact.create({ firstName: "Mike", lastName: "Sheeks", phoneNumber: "903-330-3025", email: "", primary: false, customerId: customers[7].id }),
    Contact.create({ firstName: "Camron", lastName: "Taylor", phoneNumber: "N/A", email: "", primary: false, customerId: customers[7].id }),
    Contact.create({ firstName: "James", lastName: "Bruner", phoneNumber: "903-920-4105", email: "", primary: false, customerId: customers[7].id }),
    Contact.create({ firstName: "James", lastName: "Hicks", phoneNumber: "903-780-5807", email: "", primary: false, customerId: customers[7].id }),
    Contact.create({ firstName: "Kevin", lastName: "Larsen", phoneNumber: "903-431-8368", email: "", primary: false, customerId: customers[7].id }),
    Contact.create({ firstName: "Thomas", lastName: "Moore", phoneNumber: "210-913-4099", email: "", primary: true, customerId: customers[9].id }),
    Contact.create({ firstName: "Corey", lastName: "Sharman", phoneNumber: "254-394-3290", email: "", primary: true, customerId: customers[9].id }),
    Contact.create({ firstName: "Toni", lastName: "Rios", phoneNumber: "361-461-9475", email: "", primary: false, customerId: customers[9].id }),
    Contact.create({ firstName: "Ryan", lastName: "Redding", phoneNumber: "512-214-7727", email: "", primary: false, customerId: customers[9].id }),
    Contact.create({ firstName: "Tyler", lastName: "Troppy", phoneNumber: "512-799-4427", email: "", primary: false, customerId: customers[9].id }),
    Contact.create({ firstName: "Denise", lastName: "Evans", phoneNumber: "512-718-5626", email: "", primary: false, customerId: customers[9].id }),
    Contact.create({ firstName: "Joseph", lastName: "Owens", phoneNumber: "512-948-0269", email: "", primary: false, customerId: customers[9].id }),
    Contact.create({ firstName: "Ron", lastName: "Bowen", phoneNumber: "512-284-1073", email: "", primary: false, customerId: customers[9].id }),
    Contact.create({ firstName: "David", lastName: "Salmons", phoneNumber: "512-709-3753", email: "", primary: false, customerId: customers[9].id }),
    Contact.create({ firstName: "Troy", lastName: "Moran", phoneNumber: "512-221-3859", email: "", primary: false, customerId: customers[9].id }),
    Contact.create({ firstName: "Bud", lastName: "Nolen", phoneNumber: "512-550-2214", email: "", primary: false, customerId: customers[9].id }),
    Contact.create({ firstName: "Brandon", lastName: "Linder", phoneNumber: "512-627-7005", email: "", primary: false, customerId: customers[9].id }),
    Contact.create({ firstName: "Rob", lastName: "Hardy", phoneNumber: "817-557-7147", email: "", primary: true, customerId: customers[10].id }),
    Contact.create({ firstName: "Jerad", lastName: "Barton", phoneNumber: "817-223-5913", email: "", primary: false, customerId: customers[10].id }),
    Contact.create({ firstName: "Khy", lastName: "Davis", phoneNumber: "318-208-7695", email: "", primary: false, customerId: customers[10].id }),
    Contact.create({ firstName: "Frank", lastName: "Taylor", phoneNumber: "817-709-1412", email: "", primary: false, customerId: customers[10].id }),
    Contact.create({ firstName: "Johnnie", lastName: "Frierson", phoneNumber: "469-442-6761", email: "", primary: false, customerId: customers[10].id }),
    Contact.create({ firstName: "John", lastName: "Eads", phoneNumber: "903-603-2322", email: "", primary: false, customerId: customers[10].id }),
    Contact.create({ firstName: "Charles", lastName: "Willis", phoneNumber: "346-368-9028", email: "", primary: false, customerId: customers[10].id }),
    Contact.create({ firstName: "Justin", lastName: "Sayre", phoneNumber: "469-237-7379", email: "", primary: false, customerId: customers[10].id }),
    Contact.create({ firstName: "Chris", lastName: "Evans", phoneNumber: "903-920-4969", email: "", primary: true, customerId: customers[11].id }),
    Contact.create({ firstName: "Bryce", lastName: "Elliott", phoneNumber: "815-761-9401", email: "", primary: false, customerId: customers[11].id }),
    Contact.create({ firstName: "Bobby", lastName: "Elliott", phoneNumber: "253-267-2656", email: "", primary: false, customerId: customers[11].id }),
    Contact.create({ firstName: "Michael", lastName: "Clark", phoneNumber: "972-693-6696", email: "", primary: false, customerId: customers[11].id }),
    Contact.create({ firstName: "Jarod", lastName: "Oakers", phoneNumber: "903-245-0851", email: "", primary: true, customerId: customers[12].id }),
    Contact.create({ firstName: "Michael", lastName: "Byram", phoneNumber: "432-889-6084", email: "", primary: true, customerId: customers[12].id }),
    Contact.create({ firstName: "Kasey", lastName: "Warren", phoneNumber: "713-494-9664", email: "", primary: false, customerId: customers[12].id }),
    Contact.create({ firstName: "Mike", lastName: "Leathers", phoneNumber: "432-770-0043", email: "", primary: false, customerId: customers[12].id }),
    Contact.create({ firstName: "Damon", lastName: "Heeler", phoneNumber: "432-248-4592", email: "", primary: false, customerId: customers[12].id }),
    Contact.create({ firstName: "Brandon", lastName: "Ross", phoneNumber: "", email: "", primary: false, customerId: customers[12].id }),
    Contact.create({ firstName: "Rudy", lastName: "Cerna", phoneNumber: "432-258-4408", email: "", primary: false, customerId: customers[12].id }),
    Contact.create({ firstName: "Joe", lastName: "Williams", phoneNumber: "954-325-4562", email: "joew@groundsgroup.com", primary: true, customerId: customers[15].id }),
    Contact.create({ firstName: "Jeremy", lastName: "", phoneNumber: "954-520-4265", email: "jeremy@groundsgroup.com", primary: false, customerId: customers[15].id }),
    Contact.create({ firstName: "David", lastName: "", phoneNumber: "", email: "davidw@groundsgroup.com", primary: false, customerId: customers[15].id }),
    Contact.create({ firstName: "Fernando", lastName: "Hernandez", phoneNumber: "786-412-2087", email: "fernando@lionplumbing.com", primary: true, customerId: customers[16].id }),
    Contact.create({ firstName: "Dennis", lastName: "Hudson", phoneNumber: "954-605-6214", email: "dennis@lionplumbing.com", primary: false, customerId: customers[16].id }),
    Contact.create({ firstName: "Scott", lastName: "Davis", phoneNumber: "786-402-8006", email: "daviss@msvfl.gov", primary: true, customerId: customers[17].id }),
    Contact.create({ firstName: "Chris", lastName: "Miranda", phoneNumber: "305-525-9436", email: "mirandac@msvfl.gov", primary: true, customerId: customers[17].id }),
    Contact.create({ firstName: "Jim", lastName: "McCoy", phoneNumber: "305-793-2172", email: "mccoy@msvfl.gov", primary: false, customerId: customers[17].id }),
    Contact.create({ firstName: "Mike", lastName: "Skofstad", phoneNumber: "305-793-2788", email: "skofstam@smvfl.gov", primary: false, customerId: customers[17].id }),
    Contact.create({ firstName: "Enrique", lastName: "Travieso", phoneNumber: "305-522-3886", email: "", passcode: "3486", primary: true, customerId: customers[18].id }),
    Contact.create({ firstName: "Ralph", lastName: "Henderson", phoneNumber: "305-487-3816", email: "", passcode: "0611", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "Paul", lastName: "Mendoza", phoneNumber: "305-487-3816", email: "", passcode: "3903", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "Pedro", lastName: "Gutierrez", phoneNumber: "954-683-1273", email: "", passcode: "9639", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "Carlos", lastName: "Mesa", phoneNumber: "305-753-9501", email: "", passcode: "4734", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "Kadeem", lastName: "Leon", phoneNumber: "340-642-0855", email: "", passcode: "3849", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "Rene", lastName: "Lopez", phoneNumber: "786-991-8554", email: "", passcode: "6243", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "Loudres", lastName: "Camejo", phoneNumber: "561-430-9134", email: "", passcode: "2776", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "Ralph", lastName: "Henderson", phoneNumber: "305-796-3469", email: "", passcode: "8440", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "John Paul", lastName: "Davis", phoneNumber: "", email: "", passcode: "3486", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "Eddie", lastName: "Drowne", phoneNumber: "786-574-0749", email: "", passcode: "8327", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "Paulo", lastName: "Carlini", phoneNumber: "305-972-9360", email: "", passcode: "9070", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "Tomas", lastName: "Murgado", phoneNumber: "786-376-9453", email: "", passcode: "3823", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "Luis", lastName: "Fajardo", phoneNumber: "305-487-3853", email: "", passcode: "1895", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "Phil", lastName: "Ruiz", phoneNumber: "561-386-1654", email: "", passcode: "9686", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "Octavio (Toby)", lastName: "Montes", phoneNumber: "954-401-2881", email: "", passcode: "2840", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "Heriberto (Bert)", lastName: "Rodriguez", phoneNumber: "954-683-1351", email: "", passcode: "2259", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "Pedro", lastName: "Martinez", phoneNumber: "786-296-1816", email: "", passcode: "8495", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "Alci", lastName: "Bautista", phoneNumber: "954-683-1260", email: "", passcode: "6627", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "Lazaro", lastName: "Castro", phoneNumber: "", email: "", passcode: "9382", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "Anthony", lastName: "Aheren", phoneNumber: "305-202-3931", email: "", passcode: "7521", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "Mike", lastName: "Molina", phoneNumber: "305-972-9360", email: "", passcode: "0778", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "Andres", lastName: "Ruiz", phoneNumber: "786-575-2631", email: "", passcode: "8457", primary: false, customerId: customers[18].id }),
    Contact.create({ firstName: "Joe", lastName: "", phoneNumber: "561-213-6181", email: "", passcode: "", primary: true, customerId: customers[19].id }),
    Contact.create({ firstName: "Ray", lastName: "", phoneNumber: "954-240-9697", email: "", passcode: "1162", primary: true, customerId: customers[19].id }),
    Contact.create({ firstName: "Mike", lastName: "McColgin", phoneNumber: "305-345-7053", email: "", passcode: "3219", primary: false, customerId: customers[19].id }),
    Contact.create({ firstName: "Raymond", lastName: "Arvelo", phoneNumber: "954-684-5054", email: "", passcode: "4721", primary: false, customerId: customers[19].id }),
    Contact.create({ firstName: "Luis E.", lastName: "Pizarro", phoneNumber: "954-401-3359", email: "", passcode: "7379", primary: false, customerId: customers[19].id }),
    Contact.create({ firstName: "Joseph", lastName: "Carey", phoneNumber: "954-224-5166", email: "", passcode: "4212", primary: false, customerId: customers[19].id }),
    Contact.create({ firstName: "Frank", lastName: "Pariente", phoneNumber: "954-224-1065", email: "", passcode: "6286", primary: false, customerId: customers[19].id }),
    Contact.create({ firstName: "Robert", lastName: "Cabera", phoneNumber: "954-224-6196", email: "", passcode: "0793", primary: false, customerId: customers[19].id }),
    Contact.create({ firstName: "Christian", lastName: "Colas", phoneNumber: "954-224-8939", email: "", passcode: "7493", primary: false, customerId: customers[19].id }),
    Contact.create({ firstName: "Alex", lastName: "Perez", phoneNumber: "786-316-1409", email: "", passcode: "2238", primary: false, customerId: customers[19].id }),
    Contact.create({ firstName: "Joe", lastName: "Butardo", phoneNumber: "305-360-1020", email: "", passcode: "2430", primary: false, customerId: customers[19].id }),
    Contact.create({ firstName: "Edward", lastName: "Rueda", phoneNumber: "305-205-4775", email: "", passcode: "9125", primary: false, customerId: customers[19].id }),
    Contact.create({ firstName: "Michael", lastName: "McCord", phoneNumber: "541-505-4905", email: "", passcode: "9555", primary: false, customerId: customers[19].id }),
    Contact.create({ firstName: "Dumitru", lastName: "Jurgea", phoneNumber: "954-203-3572", email: "", passcode: "8419", primary: false, customerId: customers[19].id }),
    Contact.create({ firstName: "Karel", lastName: "Gonzalez", phoneNumber: "786-383-5499", email: "", passcode: "1406", primary: false, customerId: customers[19].id }),
    Contact.create({ firstName: "Norbert", lastName: "Orozco", phoneNumber: "754-422-7048", email: "", passcode: "3267", primary: false, customerId: customers[19].id }),
    Contact.create({ firstName: "Marco", lastName: "Falcon", phoneNumber: "786-443-0653", email: "1386", passcode: "", primary: false, customerId: customers[19].id }),
    Contact.create({ firstName: "Rosanie", lastName: "Howell-Ashley", phoneNumber: "954-895-0863", email: "", passcode: "5805", primary: false, customerId: customers[19].id }),
    Contact.create({ firstName: "Manuel", lastName: "Perez", phoneNumber: "954-383-8848", email: "", passcode: "5773", primary: false, customerId: customers[19].id }),
    Contact.create({ firstName: "Keith", lastName: "Novak", phoneNumber: "305-930-2726", email: "", passcode: "4498", primary: false, customerId: customers[19].id }),
    Contact.create({ firstName: "George", lastName: "Phipps", phoneNumber: "786-886-6224", email: "", passcode: "5385", primary: false, customerId: customers[19].id }),
    Contact.create({ firstName: "Anthony", lastName: "Caparco", phoneNumber: "561-236-7111", email: "", passcode: "0054", primary: true, customerId: customers[20].id }),
    Contact.create({ firstName: "Sandra", lastName: "Barham", phoneNumber: "561-312-9130", email: "", passcode: "0067", primary: true, customerId: customers[20].id }),
    Contact.create({ firstName: "Terry", lastName: "Sluder", phoneNumber: "561-281-8052", email: "", passcode: "80", primary: true, customerId: customers[20].id }),
    Contact.create({ firstName: "Monteo", lastName: "Campbell", phoneNumber: "561-603-8298", email: "", passcode: "69", primary: false, customerId: customers[20].id }),
    Contact.create({ firstName: "Lovett", lastName: "Cummings", phoneNumber: "561-386-1738", email: "", passcode: "77", primary: false, customerId: customers[20].id }),
    Contact.create({ firstName: "Corey", lastName: "Fruge", phoneNumber: "561-510-3111", email: "", passcode: "87", primary: false, customerId: customers[20].id }),
    Contact.create({ firstName: "Trevor", lastName: "Folcarelli", phoneNumber: "561-232-8850", email: "", passcode: "34", primary: false, customerId: customers[20].id }),
    Contact.create({ firstName: "Richard", lastName: "Hawk", phoneNumber: "561-386-1655", email: "", passcode: "2", primary: false, customerId: customers[20].id }),
    Contact.create({ firstName: "Chris", lastName: "Irizarry", phoneNumber: "561-676-5825", email: "", passcode: "63", primary: false, customerId: customers[20].id }),
    Contact.create({ firstName: "Keith", lastName: "Jackson", phoneNumber: "561-386-1680", email: "", passcode: "89", primary: false, customerId: customers[20].id }),
    Contact.create({ firstName: "Ahmad", lastName: "Jones", phoneNumber: "561-335-9805", email: "", passcode: "21", primary: false, customerId: customers[20].id }),
    Contact.create({ firstName: "Mitch", lastName: "Maddren", phoneNumber: "561-379-0397", email: "", passcode: "26", primary: false, customerId: customers[20].id }),
    Contact.create({ firstName: "Adam", lastName: "Taylor", phoneNumber: "561-267-3545", email: "", passcode: "47", primary: false, customerId: customers[20].id }),
    Contact.create({ firstName: "Luis", lastName: "Vega", phoneNumber: "561-212-0651", email: "", passcode: "93", primary: false, customerId: customers[20].id }),
    Contact.create({ firstName: "Matt", lastName: "Whalen", phoneNumber: "561-301-2937", email: "", passcode: "10", primary: false, customerId: customers[20].id }),
    Contact.create({ firstName: "Joama", lastName: "Perez", phoneNumber: "786-720-1098", email: "", passcode: "11", primary: false, customerId: customers[20].id }),
    Contact.create({ firstName: "Derrick", lastName: "Koonce", phoneNumber: "561-236-9419", email: "", passcode: "19", primary: false, customerId: customers[20].id }),
    Contact.create({ firstName: "Mark", lastName: "Winn", phoneNumber: "561-345-0983", email: "", passcode: "52", primary: false, customerId: customers[20].id }),
    Contact.create({ firstName: "Miguel", lastName: "Barbosa", phoneNumber: "", email: "", passcode: "", primary: false, customerId: customers[20].id }),
    Contact.create({ firstName: "John", lastName: "Melton", phoneNumber: "305-793-6916", email: "", passcode: "miami115", primary: true, customerId: customers[21].id }),
    Contact.create({ firstName: "Charles", lastName: "Glaslow", phoneNumber: "305-322-8034", email: "", passcode: "11501", primary: false, customerId: customers[21].id }),
    Contact.create({ firstName: "Nicholas", lastName: "Marcano", phoneNumber: "786-838-5198", email: "", passcode: "11500", primary: false, customerId: customers[21].id }),
    Contact.create({ firstName: "Enrique", lastName: "Mayor", phoneNumber: "786-773-0194", email: "", passcode: "1801", primary: false, customerId: customers[21].id }),
    Contact.create({ firstName: "Maikel", lastName: "Ortiz", phoneNumber: "786-326-5005", email: "", passcode: "miamax34", primary: false, customerId: customers[21].id }),
    Contact.create({ firstName: "Raul", lastName: "Alvarez", phoneNumber: "786-217-5354", email: "", passcode: "cosita3t", primary: false, customerId: customers[21].id }),
    Contact.create({ firstName: "Yandy", lastName: "Leal", phoneNumber: "786-342-4047", email: "", passcode: "leal1974", primary: false, customerId: customers[21].id }),
    Contact.create({ firstName: "Andy", lastName: "Ruiz", phoneNumber: "786-312-2774", email: "", passcode: "9306", primary: false, customerId: customers[21].id }),
    Contact.create({ firstName: "Michel", lastName: "Diaz", phoneNumber: "786-365-0596", email: "", passcode: "51135", primary: false, customerId: customers[21].id }),
    Contact.create({ firstName: "Jorge", lastName: "Galvez", phoneNumber: "305-216-0747", email: "", passcode: "gabriel", primary: false, customerId: customers[21].id }),
    Contact.create({ firstName: "Eddy", lastName: "Suarez", phoneNumber: "786-580-7336", email: "", passcode: "Esuarez931", primary: false, customerId: customers[21].id }),
    Contact.create({ firstName: "Giovanny", lastName: "Moreira", phoneNumber: "786-597-7446", email: "", passcode: "Giomoga0024", primary: false, customerId: customers[21].id }),
    Contact.create({ firstName: "David", lastName: "Saumell", phoneNumber: "954-448-0435", email: "", passcode: "David1331", primary: false, customerId: customers[21].id }),
    Contact.create({ firstName: "Kevin", lastName: "Mulvey", phoneNumber: "305-487-3992", email: "", passcode: "Ramtruck2019", primary: false, customerId: customers[21].id }),
    Contact.create({ firstName: "Osvaldo", lastName: "Ortega", phoneNumber: "305-298-8503", email: "", passcode: "51164", primary: false, customerId: customers[21].id }),
    Contact.create({ firstName: "Mario", lastName: "Cadavid", phoneNumber: "305-301-9136", email: "", passcode: "11564", primary: false, customerId: customers[21].id }),
    Contact.create({ firstName: "Anthony", lastName: "Soto", phoneNumber: "561-405-0765", email: "", passcode: "Asoto1234", primary: false, customerId: customers[21].id }),
    Contact.create({ firstName: "David", lastName: "Amezcua", phoneNumber: "910-512-1359", email: "", passcode: "11773", primary: false, customerId: customers[21].id }),
    Contact.create({ firstName: "Marcos", lastName: "Garcia", phoneNumber: "305-525-3552", email: "", passcode: "27883", primary: false, customerId: customers[22].id }),
    Contact.create({ firstName: "Eric", lastName: "Dafau", phoneNumber: "305-281-8393", email: "", passcode: "86392", primary: false, customerId: customers[22].id }),
    Contact.create({ firstName: "Jorge", lastName: "Serrano", phoneNumber: "305-240-4973", email: "", passcode: "85835", primary: false, customerId: customers[22].id }),
    Contact.create({ firstName: "Kaz", lastName: "Kerr", phoneNumber: "305-926-0134", email: "", passcode: "43359", primary: false, customerId: customers[22].id }),
    Contact.create({ firstName: "Wilson", lastName: "Avila", phoneNumber: "786-479-0911", email: "", passcode: "23996", primary: false, customerId: customers[22].id }),
    Contact.create({ firstName: "Felix", lastName: "Torres", phoneNumber: "305-972-9416", email: "", passcode: "29731", primary: false, customerId: customers[22].id }),
    Contact.create({ firstName: "Jorge", lastName: "Bayo", phoneNumber: "305-972-5022", email: "", passcode: "23499", primary: false, customerId: customers[22].id }),
    Contact.create({ firstName: "Miguel", lastName: "Narranjo", phoneNumber: "786-781-9822", email: "", passcode: "76235", primary: false, customerId: customers[22].id }),
    Contact.create({ firstName: "Gonzalo", lastName: "Mejia", phoneNumber: "305-562-8718", email: "", passcode: "47202", primary: false, customerId: customers[22].id }),
    Contact.create({ firstName: "Santiago", lastName: "Martinez", phoneNumber: "786-312-9466", email: "", passcode: "80185", primary: false, customerId: customers[22].id })
  ])
  
  const carts = await Promise.all([
    Cart.create({status: 'open', userId: 2 }),
    Cart.create({status: 'purchased', userId: 2 }),
    Cart.create({status: 'purchased', userId: 1 }),
    Cart.create({status: 'open', userId: 1 }),
    Cart.create({status: 'purchased', userId: 2 }),
    Cart.create({status: 'purchased', userId: 2 })
  ])
  const items = await Promise.all([
    LineItem.create({ price: 500, quantity: 1, cartId: 1, productId: 1 }),
    LineItem.create({price: 600, quantity: 1, cartId: 1, productId: 2  }),
    LineItem.create({price: 700, quantity: 1, cartId: 1, productId: 3  }),
    LineItem.create({price: 800, quantity: 1, cartId: 2, productId: 1  }),
    LineItem.create({price: 900, quantity: 1, cartId: 2, productId: 2  }),
    LineItem.create({price: 100, quantity: 1, cartId: 2, productId: 3 }),
    LineItem.create({price: 900, quantity: 1, cartId: 1, productId: 4 }),
    LineItem.create({price: 100, quantity: 1, cartId: 1, productId: 5 })
  ])

  const products = await Promise.all([
    Product.create({name: '8 PORT HD RECORDER', vendor: "AVIGILON", partNumber: "VMA-ENVR1-8P8-NA", description: 'Need to Add Specs', cost: applyDiscount(3085), price: markup(applyDiscount(3085)), image: '', featured: true }),
    Product.create({name: '4 PORT HD RECORDER', vendor: "AVIGILON", partNumber: "VMA-ENVR1-8P4-NA", description: 'Add Specs later', cost: applyDiscount(2665), price: markup(applyDiscount(2665)), image: '', featured: true }),
    Product.create({name: 'H5A BULLET CAMERA', vendor: "AVIGILON", partNumber: "2.0-H5A-BO1-IR", description: '2 MP', cost: applyDiscount(1000), price: markup(applyDiscount(1000)), image: '' }),
    Product.create({name: 'H5SL BULLET CAMERA', vendor: "AVIGILON", partNumber: "2.0C-H5SL-BO1-IR", description: '2 MP', cost: applyDiscount(520), price: markup(applyDiscount(520)), image: '', featured: true }),
    Product.create({name: '180 DEGREE MULTISENSOR', vendor: "AVIGILON", partNumber: "9C-H4A-3MH-180", description: '9MP', cost: applyDiscount(1655), price: markup(applyDiscount(1655)), image: '' }),
    Product.create({name: '270 DEGREE MULTISENSOR', vendor: "AVIGILON", partNumber: "9C-H4A-3MH-270", description: '9MP', cost: applyDiscount(1655), price: markup(applyDiscount(1655)), image: '' }),
    Product.create({name: '360 DEGREE MULTISENSOR', vendor: "AVIGILON", partNumber: "12C-H4A-4MH-360", description: 'the blend will make you want more', cost: applyDiscount(1905), price: markup(applyDiscount(1905)), image: '' }),
    Product.create({name: 'ANALYTICS PLUS', vendor: "DAHUA", partNumber: "N45EF63", description: '4MP', cost: 190, price: markup(190), image: '' }),
    Product.create({name: 'STARLIGHT VARI-FOCAL', vendor: "DAHUA", partNumber: "N45DB7Z", description: '4MP', cost: 290, price: markup(290), image: '' }),
    Product.create({name: 'AI NETWORK CAMERA', vendor: "DAHUA", partNumber: "HNC5I142T-ASEN236", description: '4MP', cost: 179, price: markup(179), image: '' }),
    Product.create({name: 'STARLIGHT BULLET NETWORK CAMERA', vendor: "DAHUA", partNumber: "HNC3V141T-IR-ZS-S2", description: 'Test', cost: 139, price: markup(139), image: '' }),
    Product.create({name: 'STARLIGHT FIXED TURRET CAMERA', vendor: "DAHUA", partNumber: "HNC3V341TM-IRAS-S228", description: '4MP', cost: 80, price: markup(80), image: '' }),
    Product.create({name: 'FIXED LENS IR MINI', vendor: "DAHUA", partNumber: "HNC3V241E-IR36", description: '4MP, 2.8MM Lens', cost: 75, price: markup(75), image: '' }),
    Product.create({name: 'LIGHT AI IR FIXED BULLET CAMERA', vendor: "DAHUA", partNumber: "HNC3I141E-IRAS28", description: '4MP', cost: 89, price: markup(89), image: '' }),
    Product.create({name: 'HD ANALOG CAMERA', vendor: "DH VISION", partNumber: "DH-IDF-480WN(ZA)-V3(2.8mm)", description: '2MP, 2.8MM Lens', cost: 19.50, price: markup(19.50), image: '' }),
    Product.create({name: 'HD ANALOG BULLET CAMERA', vendor: "DH VISION", partNumber: "DH-UBV7500W", description: '5MP', cost: 31.5, price: markup(31.5), image: '' }),
    Product.create({name: 'UNIVIEW TURRET DOME', vendor: "DH Vision", partNumber: "IPC3614SR3-DPF28M", description: '4MP', cost: 75, price: markup(75), image: '' }),
    Product.create({name: 'FIXED LENS UNIVIEW BULLET CAMERA', vendor: "DH VISION", partNumber: "IPC2124SR3-DPF36", description: '4MP', cost: 75, price: markup(75), image: '' }),
    Product.create({name: 'VARI-FOCAL UNIVIEW BULLET CAMERA', vendor: "DH VISION", partNumber: "IPC232EBR-DPZ28", description: '4MP', cost: 130, price: markup(130), image: '' }),
    Product.create({name: 'UNIVIEW 4K FIXED LENS BULLET CAMERA', vendor: "DH VISION", partNumber: "IPC2128SR3-DPF40", description: '4K', cost: 120, price: markup(120), image: '' }),
    Product.create({name: 'OUTDOOR PENDENT MOUNT ADAPTER', vendor: "AVIGILON", partNumber: "H4AMH-AD-PEND1", description: '', cost: 160, price: markup(160), image: '' }),
    Product.create({name: 'DOME AND BUBBLE COVER', vendor: "AVIGILON", partNumber: "H4AMH-DO-COVR1", description: '', cost: 160, price: markup(160), image: '' }),
    Product.create({name: 'PENDANT WALL MOUNT ADAPTER', vendor: "AVIGILON", partNumber: "IRPTZ-MNT-WALL1", description: '', cost: 95, price: markup(95), image: '' }),
    Product.create({name: 'PENDAN NPT MOUNT ADAPTER', vendor: "AVIGILON", partNumber: "IRPTZ-MNT-NPTA-1", description: '', cost: 55, price: markup(55), image: '' }),
    Product.create({name: 'OUTDOOR SURFACE MOUNT ADAPTER', vendor: "AVIGILON", partNumber: "H4AMH-AD-DOME1", description: '', cost: 160, price: markup(160), image: '' }),
    Product.create({name: 'IN CEILING ADAPTER', vendor: "AVIGILON", partNumber: "H4AMH-AD-CEIL1", description: '', cost: 150, price: markup(150), image: '' }),
    Product.create({name: 'JUNCTION BOX', vendor: "AVIGILON", partNumber: "H4-BO-JBOX1", description: '', cost: 90, price: markup(90), image: '' }),
    Product.create({name: 'JUNCTION BOX', vendor: "ADI", partNumber: "PFA121", description: '', cost: 17.99, price: markup(17.99), image: '' }),
    Product.create({name: 'CORNER MOUNT', vendor: "ENS", partNumber: "PFA151", description: '', cost: 20, price: markup(20), image: '' }),
    Product.create({name: '4 CHANNEL DVR', vendor: "DH VISION", partNumber: "PVR04H1-X", description: '', cost: 53, price: markup(53), image: '' }),
    Product.create({name: '8 CHANNEL DVR', vendor: "DH VISION", partNumber: "PVR08H1-X", description: '', cost: 77, price: markup(77), image: '' }),
    Product.create({name: '16 CHANNEL DVR', vendor: "DH VISION", partNumber: "PVR16H1-X", description: '', cost: 125, price: markup(125), image: '' }),
    Product.create({name: '32 CHANNEL DVR', vendor: "DH VISION", partNumber: "PVR32H2-X", description: '', cost: 270, price: markup(270), image: '' }),
    Product.create({name: 'UNIVIEW 8 CHANNEL NVR', vendor: "UNIVIEW", partNumber: "NVR301-08L-P8", description: '', cost: 93, price: markup(93), image: '' }),
    Product.create({name: 'UNIVIEW 16 CHANNEL NVR', vendor: "UNIVISION", partNumber: "NVR302-16E-P16-B", description: '', cost: 280, price: markup(280), image: '' })
  ])

  const categories = await Promise.all([
    Category.create({ name: 'BULLET CAMERAS', description: 'All Bullet Cameras', featured: true }),
    Category.create({ name: 'ACCESSORIES', description: 'All Camera Accessories' }),
    Category.create({ name: 'AVIGILON', description: 'All Avigilon Products' }),
    Category.create({ name: 'DAHUA', description: 'All Dahua Products', featured: true }),
    Category.create({ name: 'UNIVIEW', description: 'All Uniview Products' }),
    Category.create({ name: 'MULTISENSOR CAMERAS', description: 'All Multisensor Cameras' }),
    Category.create({ name: 'TURRET DOME CAMERAS', description: 'All Turret Dome Cameras' }),
    Category.create({ name: 'DVRS', description: 'All DVRs' }),
    Category.create({ name: 'NVRS', description: 'All NVRs' })
  ])

  const productCategories = await Promise.all([
    ProductCategory.create({ categoryId: 1, productId: 3 }),
    ProductCategory.create({ categoryId: 1, productId: 4 }),
    ProductCategory.create({ categoryId: 1, productId: 11 }),
    ProductCategory.create({ categoryId: 1, productId: 14 }),
    ProductCategory.create({ categoryId: 1, productId: 15 }),
    ProductCategory.create({ categoryId: 1, productId: 16 }),
    ProductCategory.create({ categoryId: 1, productId: 18 }),
    ProductCategory.create({ categoryId: 1, productId: 19 }),
    ProductCategory.create({ categoryId: 1, productId: 20 }),
    ProductCategory.create({ categoryId: 2, productId: 21 }),
    ProductCategory.create({ categoryId: 2, productId: 22 }),
    ProductCategory.create({ categoryId: 2, productId: 23 }),
    ProductCategory.create({ categoryId: 2, productId: 24 }),
    ProductCategory.create({ categoryId: 2, productId: 25 }),
    ProductCategory.create({ categoryId: 2, productId: 26 }),
    ProductCategory.create({ categoryId: 2, productId: 27 }),
    ProductCategory.create({ categoryId: 2, productId: 28 }),
    ProductCategory.create({ categoryId: 2, productId: 29 }),
    ProductCategory.create({ categoryId: 3, productId: 1 }),
    ProductCategory.create({ categoryId: 3, productId: 2 }),
    ProductCategory.create({ categoryId: 3, productId: 3 }),
    ProductCategory.create({ categoryId: 3, productId: 4 }),
    ProductCategory.create({ categoryId: 3, productId: 5 }),
    ProductCategory.create({ categoryId: 3, productId: 6 }),
    ProductCategory.create({ categoryId: 3, productId: 7 }),
    ProductCategory.create({ categoryId: 3, productId: 21 }),
    ProductCategory.create({ categoryId: 3, productId: 22 }),
    ProductCategory.create({ categoryId: 3, productId: 23 }),
    ProductCategory.create({ categoryId: 3, productId: 24 }),
    ProductCategory.create({ categoryId: 3, productId: 25 }),
    ProductCategory.create({ categoryId: 3, productId: 26 }),
    ProductCategory.create({ categoryId: 3, productId: 27 }),
    ProductCategory.create({ categoryId: 4, productId: 8 }),
    ProductCategory.create({ categoryId: 4, productId: 9 }),
    ProductCategory.create({ categoryId: 4, productId: 10 }),
    ProductCategory.create({ categoryId: 4, productId: 11 }),
    ProductCategory.create({ categoryId: 4, productId: 12 }),
    ProductCategory.create({ categoryId: 4, productId: 13 }),
    ProductCategory.create({ categoryId: 4, productId: 14 }),
    ProductCategory.create({ categoryId: 5, productId: 34 }),
    ProductCategory.create({ categoryId: 5, productId: 35 }),
    ProductCategory.create({ categoryId: 6, productId: 5 }),
    ProductCategory.create({ categoryId: 6, productId: 6 }),
    ProductCategory.create({ categoryId: 6, productId: 7 }),
    ProductCategory.create({ categoryId: 7, productId: 12 }),
    ProductCategory.create({ categoryId: 7, productId: 17 }),
    ProductCategory.create({ categoryId: 8, productId: 30 }),
    ProductCategory.create({ categoryId: 8, productId: 31 }),
    ProductCategory.create({ categoryId: 8, productId: 32 }),
    ProductCategory.create({ categoryId: 8, productId: 33 }),
    ProductCategory.create({ categoryId: 9, productId: 1 }),
    ProductCategory.create({ categoryId: 9, productId: 2 }),
    ProductCategory.create({ categoryId: 9, productId: 34 }),
    ProductCategory.create({ categoryId: 9, productId: 35 }),
  ])

  const bids =  await Promise.all([
    Bid.create({ title: "Test One", status: "open", userId: 1, customerId: customers[0].id }),
    Bid.create({ title: "Test Two", status: "pending", userId: 1, customerId: customers[1].id }),
    Bid.create({ title: "Test Three", status: "pending", userId: 1, customerId: customers[2].id }),
    Bid.create({ title: "Test Four", status: "approved", userId: 1, customerId: customers[3].id }),
    Bid.create({ title: 'Test Five', status: "declined", userId: 1, customerId: customers[4].id })
  ])

  const bidAreas = await Promise.all([
    BidArea.create({ title: "Back Parking", bidId: 1 }),
    BidArea.create({ title: "Front Parking", bidId: 1 }),
    BidArea.create({ title: "Front Gate", bidId: 1 }),
    BidArea.create({ title: "Side Fence", bidId: 1 }),
    BidArea.create({ title: "Car Lot", bidId: 1 }),
    BidArea.create({ title: "Shipping Dock", bidId: 1 }),
    BidArea.create({ title: "Back Parking", bidId: 2 }),
    BidArea.create({ title: "Front Parking", bidId: 2 }),
    BidArea.create({ title: "Front Gate", bidId: 2 }),
    BidArea.create({ title: "Car Lot", bidId: 2 }),
    BidArea.create({ title: "Shipping Dock", bidId: 2 })
  ])

  const areaProducts = await Promise.all([
    AreaProduct.create({ bidAreaId: 1, price: findProp(products, 3, 'price'), cost: findProp(products, 3, 'cost'), productId: 3, qty: 4 }),
    AreaProduct.create({ bidAreaId: 1, price: findProp(products, 2, 'price'), cost: findProp(products, 2, 'cost'), productId: 2, qty: 3 }),
    AreaProduct.create({ bidAreaId: 1, price: findProp(products, 1, 'price'), cost: findProp(products, 1, 'cost'), productId: 1, qty: 1 }),
    AreaProduct.create({ bidAreaId: 1, price: findProp(products, 4, 'price'), cost: findProp(products, 4, 'cost'), productId: 4, qty: 1 }),
    AreaProduct.create({ bidAreaId: 1, price: findProp(products, 10, 'price'), cost: findProp(products, 10, 'cost'), productId: 10, qty: 3 }),
    AreaProduct.create({ bidAreaId: 1, price: findProp(products, 12, 'price'), cost: findProp(products, 12, 'cost'), productId: 12, qty: 2 }),
    AreaProduct.create({ bidAreaId: 2, price: findProp(products, 3, 'price'), cost: findProp(products, 3, 'cost'), productId: 3, qty: 4 }),
    AreaProduct.create({ bidAreaId: 3, price: findProp(products, 2, 'price'), cost: findProp(products, 2, 'cost'), productId: 2, qty: 3 }),
    AreaProduct.create({ bidAreaId: 4, price: findProp(products, 1, 'price'), cost: findProp(products, 1, 'cost'), productId: 1, qty: 1 }),
    AreaProduct.create({ bidAreaId: 5, price: findProp(products, 4, 'price'), cost: findProp(products, 4, 'cost'), productId: 4, qty: 1 }),
    AreaProduct.create({ bidAreaId: 6, price: findProp(products, 10, 'price'), cost: findProp(products, 10, 'cost'), productId: 10, qty: 3 }),
    AreaProduct.create({ bidAreaId: 7, price: findProp(products, 12, 'price'), cost: findProp(products, 12, 'cost'), productId: 12, qty: 2 }),
    AreaProduct.create({ bidAreaId: 8, price: findProp(products, 3, 'price'), cost: findProp(products, 3, 'cost'), productId: 3, qty: 4 }),
    AreaProduct.create({ bidAreaId: 9, price: findProp(products, 2, 'price'), cost: findProp(products, 2, 'cost'), productId: 2, qty: 3 }),
    AreaProduct.create({ bidAreaId: 10, price: findProp(products, 1, 'price'), cost: findProp(products, 1, 'cost'), productId: 1, qty: 1 }),
    AreaProduct.create({ bidAreaId: 11, price: findProp(products, 4, 'price'), cost: findProp(products, 4, 'cost'), productId: 4, qty: 1 }),
  ])

  const reviews = await Promise.all([
    Review.create({ content: "Delicious", rating: 4, productId: 1 }),
    Review.create({ content: "It's Great!", rating: 1, productId: 1 }),
    Review.create({ content: "I'm not a fan", rating: 2, productId: 2 }),
  ])
  console.log(`seeded ${users.length} users, ${items.length} items, ${reviews.length} reviews, ${products.length} products, ${productCategories.length} productCategories, ${carts.length} carts, ${bids.length} bids, ${bidAreas.length} bidAreas, and ${categories.length} categories`)
  console.log(`seeded successfully`)
}

seed()
  .catch(err => {
    console.error(err.message)
    console.error(err.stack)
    process.exitCode = 1
  })
  .then(() => {
    console.log(chalk.bgBlue.white.bold('closing db connection'))
    db.close()
    console.log(chalk.bgRed.white.bold('db connection closed'))
  })

console.log('seeding...')
